cache:
  paths:
    - wp-content/themes/node_modules/
    - wp-content/themes/bower_components/
    - wordpress
stages:
- build
build:
  stage: build
  only:
    - tags
  tags: ['shared']
  before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  script:
  - cp .htaccess.permalinks wordpress/.htaccess
  - cd wp-content/themes/yocto
  - npm install
  - bower install
  - gulp